Platzi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(route='', view=views.PostFeedView.as_view(), name='feed'),
    path(route='posts/new/', view=views.CreatePostView.as_view(), name='create'),
    path(route='posts/<int:pk>/', view=views.PostDetailView.as_view(), name='detail'),
    path(route='posts/delete/<int:pk>/', view=views.delete_post, name="delete"),
]

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/instagram-2-1.svg" type="image/x-icon">
    {% block head %}
    {% endblock head %}

</head>

{% block content %}
replace me
{% endblock %}

</html>

templates/nav.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/nav.css' %}">

{% block navbar %}

<header>
    <nav id="navbar">
        <div>
            <a href="{% url 'posts:feed' %}">
                <img id="logo"
                    src="https://raw.githubusercontent.com/leungwensen/svg-icon/b84b3f3a3da329b7c1d02346865f8e98beb05413/dist/svg/logos/instagram.svg"
                    alt="Instagram logo">
            </a>
        </div>

        <div id="icons">
            <a href="{% url 'posts:feed' %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home-2" width="34"
                    height="34" viewBox="0 0 24 24" stroke-width="1.5" stroke="#343434" fill="none"
                    stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <polyline points="5 12 3 12 12 3 21 12 19 12" />
                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
                    <rect x="10" y="12" width="4" height="4" />
                </svg>
            </a>

            <a href="{% url 'posts:create' %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-square-plus" width="34"
                    height="34" viewBox="0 0 24 24" stroke-width="1.5" stroke="#343434" fill="none"
                    stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <rect x="4" y="4" width="16" height="16" rx="2" />
                    <line x1="9" y1="12" x2="15" y2="12" />
                    <line x1="12" y1="9" x2="12" y2="15" />
                </svg>
            </a>

            <a href="{% url 'users:detail' request.user.username %}">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="34" height="34"
                    viewBox="0 0 24 24" stroke-width="1.5" stroke="#343434" fill="none" stroke-linecap="round"
                    stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <circle cx="12" cy="7" r="4" />
                    <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                </svg>
            </a>
        </div>
    </nav>
</header>

{% endblock navbar %}