Platzi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static  
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(route='', view=views.PostFeedView.as_view(), name='feed'),
    path(route='posts/new/', view=views.CreatePostView.as_view(), name='create'),
    path(route='posts/<int:pk>/', view=views.PostDetailView.as_view(), name='detail'),
    path(route='posts/delete/<int:pk>/', view=views.delete_post, name="delete"),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(route='login/', view=views.LoginView.as_view(), name='login'),
    path(route='users/logout/', view=views.log_out_view, name='logout'),
    path(route='signup/', view=views.SignupView.as_view(), name='signup'),
    path(route='me/profile/', view=views.UpdateProfileView.as_view(), name='update'),
    path(route='<str:username>/', view=views.UserDetailView.as_view(), name='detail'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=100, blank=True)
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.username    

users/forms.py
from django import forms
from django.forms.widgets import EmailInput
from .models import Profile
from django.contrib.auth.models import User


class ProfileForm(forms.Form):
    bio = forms.CharField(max_length=250, required=True)
    phone_number = forms.CharField(max_length=20)
    website = forms.URLField(max_length=100)
    picture = forms.ImageField(required=True)


class SingUpForm(forms.Form):
    username = forms.CharField(min_length=4, max_length=20)
    password = forms.CharField(
        min_length=7, max_length=100, widget=forms.PasswordInput())
    password_confirm = forms.CharField(
        min_length=7, max_length=100, widget=forms.PasswordInput())
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100, widget=EmailInput())

    def clean_username(self):
        username = self.cleaned_data['username']
        query = User.objects.filter(username=username).exists()

        if query:
            raise forms.ValidationError(('Username is alredy taken!'), code='invalid')

        return username

    def clean(self):
        data = super().clean()

        password = data['password']
        password_confirm = data['password_confirm']

        if password != password_confirm:
            raise forms.ValidationError(('Passwords do not match!'), code='invalid')

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirm')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

"""
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'password']


class RawUserForm(forms.Form):
    website = forms.URLField()
    bio = forms.CharField()
    phone_number = forms.CharField()
    picture = forms.ImageField()
"""

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages.api import error
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth.models import User
from django.contrib import messages

from .forms import ProfileForm, SingUpForm
from .models import Profile
from posts.models import Post


class UserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')

        return context


"""
def sign_up(request):
    form = RawUserForm(request.POST or None)

    if form.is_valid(): 
            User.objects.create(**form.cleaned_data)

    context = {
        'form': form,
    }

    return render(request, 'users/sign_up.html', context)
"""


class LoginView(LoginView):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.get_form().errors:
            context['error'] = 'Invalid user or password!'

        return context


def log_in_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            # Se usa el nombre de la url definida en el archivo urls.py
            return redirect('posts:feed')
        else:
            return render(request, 'users/login.html', {'error': 'Invalid user or password'})

    return render(request, 'users/login.html', {})


class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'users/logout.html'


@login_required()
def log_out_view(request):
    logout(request)
    return redirect('users:login')


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SingUpForm
    success_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['error'] = self.get_form().errors

        return context

    def form_valid(self, form):
        messages.success(
            request=self.request, message='Account created successfully!')
        form.save()

        return super().form_valid(form)

    def form_invalid(self, form):

        return super().form_invalid(form)


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:feed')

    if request.method == 'POST':
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
        else:
            return render(request, 'users/signup.html', {'error': form.errors})

    form = SingUpForm()

    return render(request, 'users/signup.html', {'form': form})


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'bio', 'phone_number', 'picture']

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        username = self.object.user.username

        return reverse('users:detail', kwargs={'username': username})


@login_required()
def update_profile(request):
    form = ProfileForm()
    profile = request.user.profile
    if request.method == 'POST':
        # request.Files para pasar archivos
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            profile.website = data['website']
            profile.bio = data['bio']
            profile.phone_number = data['phone_number']
            profile.picture = data['picture']
            profile.save()

            # Como la url detail recibe como parametro el nombre de usuario
            # se pasa como kwargs y en forma de diccionario
            # Tambien se usa reverse para crear la url ya que redirect no la puede
            # crear como users:detail y el argumento que hay que pasarles
            url = reverse('users:detail', kwargs={
                          'username': request.user.username})
            return redirect(url)
        else:
            return render(request, 'users/update_profile.html', {'form': form})

    context = {
        'user': request.user,
        'profile': profile,
        'form': form,
    }

    return render(request, 'users/update_profile.html', context)


"""
def create_user(request):
    if request.method == 'POST':
        form = UserForm()
    context = { }
    return render(request, 'create_user.html', context)
"""


"""
def create_user(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = UserForm()

    context = {
        'form': form,
    }

    return render(request, 'create_user.html', context)
"""

templates/users/detail.html
{% extends 'base.html' %}
{% block content %}

{% include 'nav.html' %}


<p style="margin-top: 100px;">@{{ user.username }}</p>
<p>{{ user.get_full_name }}</p>
{% if user.profile.picture %}
    <img class="border-img-user" src="{{ user.profile.picture.url }}" alt="user_picture" width="200" height="200">
{% endif %}
<p>{{ user.profile.bio }}</p>
<p>{{ user.profile.website }}</p>
<p>{{ user.profile.phone_number }}</p>
<p>{{ user.profile.created }}</p>

<br>
<p>-----------------------------------------</p>
{% if posts %}
    {% for post in posts %}
        <img class="posts" src="{{ post.photo.url }}" alt="{{ post.photo }}" width="300" height="300">
        {% if request.user.id == post.user.id %}
            <a href="{% url 'posts:delete' post.id %}">Delete</a>
        {% endif %}
        <br>
        <strong>{{ post.title }}</strong> - {{ post.created }}
        <br><br><br>
    {% endfor %}
{% else %}
    <p>There are no posts yet</p>
{% endif %}


{% if user == request.user %}
    <a href="{% url 'users:update' %}" style="vertical-align:middle;margin:10px 50px;" class="btn btn-success">Update</a>
{% else %}
    <a href="#" style="vertical-align:middle;margin:10px 50px;" class="btn btn-success">Follow</a>
{% endif %}


{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}


{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<title>Log in</title>
{% endblock head %}


{% block content %}

<body>
    <div class="container">

        {% if messages %}
        <div class="warning-alert">
            {% for message in messages %}
            <p id="succes-alert"><strong>{{ message }}</strong></p>
            {% endfor %}
        </div>
        {% endif %}


        {% if form.errors %}
        <div class="warning-alert">

            {% for field in form %}
            {% for error in field.errors %}
            <div>
                <p id="fail-alert"><strong>{{ error }}</strong></p>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div>
                <p id="fail-alert"><strong>{{ error }}</strong></p>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="login-form-container">
            <form action="{% url 'users:login' %}" method="POST" class="login-form">{% csrf_token %}
                <label for="username"></label>
                <input type="text" class="username" id="username" name="username" placeholder="Username" required>

                <label for="password"></label>
                <input type="password" class="password" id="password" name="password" placeholder="Password"
                    autocapitalize="off" required>

                <button type="submit">Login</button>
                <p class="text-singup">Don't have an account? <a class="text-singup"
                        href="{% url 'users:signup' %}">Sign
                        up!</a></p>
            </form>
        </div>
    </div>
</body>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap" rel="stylesheet">
<title>Register!</title>
{% endblock head %}

{% block content %}


{% if form.errors %}
<div class="warning-alert">

    {% for field in form %}
    {% for error in field.errors %}
    <div>
        <p id="fail-alert"><strong>{{ error }}</strong></p>
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div>
        <p id="fail-alert"><strong>{{ error }}</strong></p>
    </div>
    {% endfor %}
</div>
{% endif %}

<body>
    <div class="login-form-container">
        <form action="{% url 'users:signup' %}" method="POST" class="login-form"> {% csrf_token %}
            <label for="email"></label>
            <input type="email" class="email" id="email" placeholder="Email" name="email" maxlength="100" required>

            <label for="username"></label>
            <input type="text" class="username" id="username" placeholder="Username" name="username" maxlength="100"
                required>

            <label for="password"></label>
            <input type="password" class="password" id="password" placeholder="Password" name="password"
                autocapitalize="off" minlength="7" required>

            <label for="confir-password"></label>
            <input type="password" class="password" id="password" placeholder="Confirm password" name="password_confirm"
                minlength="7" autocapitalize="off" required>


            <label for="first-name"></label>
            <input type="text" class="first-name" id="first-name" name="first_name" maxlength="100"
                placeholder="First name" required>

            <label for="last-name"></label>
            <input type="text" class="last-name" id="last-name" name="last_name" maxlength="100" placeholder="Last name"
                required>

            <button type="submit">Sign up</button>
            <p class="text-singup">Already have an account? <a class="text-singup"
                    href="{% url 'users:login' %}">Login!</a></p>

        </form>
    </div>
</body>
{% endblock content %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block content %}

{% include 'nav.html' %}


<h1>@{{ user.username }}</h1>
<h2>{{ user.get_full_name }}</h2>

<form method="POST" action="{% url 'users:update' %}" enctype="multipart/form-data"> {% csrf_token %}

    {% if profile.picture %}
        <img src="{{ profile.picture.url }}" width="100" height="150" alt="profile_picture_user"/>
    {% else %}
        {% load static %}
        <img src="{% static '/img/sinfoto.png' %}" width="150" height="150" alt="profile_picture_user_default"/>
    {% endif %}
    <br><br>

    <label>Bio: </label>
    <input 
        name="bio" 
        type="text" 
        maxlength="250" 
        value="{% if form.errors %}{{ form.bio.value }}{% else %}{{ profile.bio }}{% endif %}"
    />
    {% for error in form.bio.errors %}
        <p style="color : red;">{{ error }}!</p>
    {% endfor %}
    <br><br>

    <label>Phone number: </label>
    <input 
        name="phone_number" 
        type="number" 
        maxlength="20" 
        value="{% if form.errors %}{{ form.bio.phone_number }}
            {% else %}{{ profile.phone_number }}
            {% endif %}"
        >
    {% for error in form.phone_number.errors %}
        <p style="color : red;">{{ error }}!</p>
    {% endfor %}
    <br><br>

    <label>Image:</label>
    <input 
        name="picture" 
        type="file"
    >
    {% for error in form.picture.errors %}
        <p style="color : red;">{{ error }}!</p>
    {% endfor %}
    <br><br>

    <label>Website:</label>
    <input 
        name="website" 
        type="url" 
        value="{% if form.errors %}{{ form.website.value}}
                {% else %}{{ profile.website }}
                {% endif %}"
    >
    {% for error in form.website.errors %}
        <p style="color : red;">{{ error }}!</p>
    {% endfor %}
    <br><br>

    <input type="submit" value="Save" /> 

</form>
<br>
<a href="{% url 'users:logout' %}"  class="btn btn-success">Log out</a>


{% endblock content %}